### ISSUE TITLE
I get an error on service.yaml

### ISSUE THREAD

**Issue by sbellanger** [actived/microsoft-teams-notifier#1]
Hello, I copy paste your exemple 
    # ACTIVED MICROSOFT TEAMS NOTIFIER
    actived_ms_teams_handler:
        class: Actived\MicrosoftTeamsNotifier\Handler\MicrosoftTeamsHandler
            arguments:
                $webhookDsn: '%env(ACTIVED_MS_TEAMS_DSN)%'
                $level: 'error'
                $title: 'Message title'
                $subject: 'Message subject'
                $emoji: '&#x1F6A8'
                $color: '#fd0404'
                $format: '[%datetime%] %channel%.%level_name%: %message%'

and I get an error 

The file "/mnt/c/apps/cqr/src/../config/services.yaml" does not contain valid YAML: A colon cannot be used in an unquoted mapping value at line 43 (near " $color: '#fd0404'") in /mnt/c/apps/cqr/src/../config/services.yaml (which is being imported from "/mnt/c/apps/cqr/src/Kernel.php").

Can you help
Thanks

**Comment by actived** [comment]
Hi @sbellanger, thank you for using ACTIVED Teams Notifier. Probably your 'yaml' file contains bad alignment.
Could you please review the file structure and make sure the spaces between different configuration parts are well respected? - see examle below:

```yaml
    # ACTIVED MICROSOFT TEAMS NOTIFIER
    actived_ms_teams_handler:
        class: Actived\MicrosoftTeamsNotifier\Handler\MicrosoftTeamsHandler
        arguments:
            $webhookDsn: '%env(ACTIVED_MS_TEAMS_DSN)%'
            $title: '%env(ACTIVED_MS_TEAMS_TITLE)%'
            $webhookDsn: '%env(ACTIVED_MS_TEAMS_DSN)%'
            $level: 'error'
            $title: 'Message title'
            $subject: 'Message subject'
            $emoji: '&#x1F6A8'
            $color: '#fd0404'
            $format: '[%datetime%] %channel%.%level_name%: %message%'
```

If problem persists, please give us a sign. Also you can have a look on this article to get more information about how to setup the tool:

https://medium.com/actived/microsoft-teams-notifications-with-monolog-and-custom-handler-fac92997ede6

Many thanks,

Actived Team
