### ISSUE TITLE
non-existent parameter "datetime"

### ISSUE THREAD

**Issue by FabienVINCENT** [actived/microsoft-teams-notifier#6]
Hi.
I'm using symofny 5.4.
By following  [this tutorial](https://medium.com/actived/microsoft-teams-notifications-with-monolog-and-custom-handler-fac92997ede6), I have an error
`You have requested a non-existent parameter "datetime".`
Any tips to try to find the problem ?

**Comment by actived** [comment]
Hi @FabienVINCENT, could you plese send more information about:
- what is your config for monolog: > handlers: ... ?
- what is the log message from log file ?
- does the error appear in previous version of Sumfony (5.2.*)?

**Comment by FabienVINCENT** [comment]
My config/services.yaml
```
actived_ms_teams_handler:
        class: Actived\MicrosoftTeamsNotifier\Handler\MicrosoftTeamsHandler
        arguments:
            $webhookDsn: '%env(ACTIVED_MS_TEAMS_DSN)%'
            $level: 'error'
            $title: 'Erreur'
            $emoji:  '&#x1F6A8'
            $color: '#fd0404'
            $format: '[%datetime%] %channel%.%level_name%: %message%'
```


```
# Issue https://github.com/symfony/monolog-bundle/issues/405
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50
        grouped:
            type:    group
            members: [teams, deduplicated]
        teams:
            type: service
            id: actived_ms_teams_handler
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'your@email.fr'
            to_email: ['my@email.fr']
            subject: 'Erreur : %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```

I don't have any other log.

I can't try with other symfony version for the moment, I have to try on a new symfony project
